### ISSUE TITLE
Screenshot with PowerBtn & HomeBtn not working on S7edge SM-G935F

### ISSUE THREAD

**Issue by sooxt98** [8890dev/android_device_samsung_hero2lte#2]
![img_343_5](https://cloud.githubusercontent.com/assets/13378059/22920942/8383e402-f2d2-11e6-82dd-f71ae417ff53.jpg)

**Comment by jesec** [comment]
Please use volume- + power.

**Comment by sooxt98** [comment]
Thank you so much
