### ISSUE TITLE
Whole Phone Crashed and reboot when Pressing the Square Btn on battery windows in MultiWindows mode

### ISSUE THREAD

**Issue by sooxt98** [8890dev/android_device_samsung_hero2lte#3]
![app_crash](https://cloud.githubusercontent.com/assets/13378059/22923122/2757d522-f2db-11e6-830d-11e1546fb2f6.jpg)

**Comment by jesec** [comment]
This is not related to device tree. It could be a framework-level problem. I am afraid that I can not help with this.
